#############################################################################
# Makefile for building: TankAssignment
# Generated by qmake (2.01a) (Qt 4.8.7) on: Mon May 15 12:07:28 2017
# Project:  TankAssignment.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile TankAssignment.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -g $(DEFINES)
CXXFLAGS      = -m64 -pipe -g $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I. -I../common
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)   -L/usr/lib/nvidia-352/ -lGLEW -lglut -lGL 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = main.cpp \
		../common/Shader.cpp \
		../common/Vector.cpp \
		../common/Matrix.cpp \
		../common/Mesh.cpp \
		../common/Texture.cpp \
		../common/SphericalCameraManipulator.cpp 
OBJECTS       = build/main.o \
		build/Shader.o \
		build/Vector.o \
		build/Matrix.o \
		build/Mesh.o \
		build/Texture.o \
		build/SphericalCameraManipulator.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		TankAssignment.pro
QMAKE_TARGET  = TankAssignment
DESTDIR       = 
TARGET        = TankAssignment

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TankAssignment.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf
	$(QMAKE) -o Makefile TankAssignment.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile TankAssignment.pro

dist: 
	@$(CHK_DIR_EXISTS) build/TankAssignment1.0.0 || $(MKDIR) build/TankAssignment1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/TankAssignment1.0.0/ && (cd `dirname build/TankAssignment1.0.0` && $(TAR) TankAssignment1.0.0.tar TankAssignment1.0.0 && $(COMPRESS) TankAssignment1.0.0.tar) && $(MOVE) `dirname build/TankAssignment1.0.0`/TankAssignment1.0.0.tar.gz . && $(DEL_FILE) -r build/TankAssignment1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_clean: 

####### Compile

build/main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

build/Shader.o: ../common/Shader.cpp ../common/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Shader.o ../common/Shader.cpp

build/Vector.o: ../common/Vector.cpp ../common/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Vector.o ../common/Vector.cpp

build/Matrix.o: ../common/Matrix.cpp ../common/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Matrix.o ../common/Matrix.cpp

build/Mesh.o: ../common/Mesh.cpp ../common/Mesh.h \
		../common/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Mesh.o ../common/Mesh.cpp

build/Texture.o: ../common/Texture.cpp ../common/Texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Texture.o ../common/Texture.cpp

build/SphericalCameraManipulator.o: ../common/SphericalCameraManipulator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SphericalCameraManipulator.o ../common/SphericalCameraManipulator.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

